apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-webui-deployment
  namespace: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: open-webui
        image: ghcr.io/lintasarta/open-webui:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "32"
            memory: 128Gi
          requests:
            cpu: "8"
            memory: 16Gi
        env:
        - name: ENABLE_OPENAI_API
          value: "True"
        - name: OPENAI_API_KEY
          value: sk-G1_wkZ37sEmY4eqnGdcNig
        - name: OPENAI_API_BASE_URL
          value: http://10.250.30.225:4000/v1
        - name: WEBUI_NAME
          value: DekaWicara
        - name: WEBUI_AUTH
          value: "True"
        - name: AIOHTTP_CLIENT_TIMEOUT
          value: "300"
        tty: true
        volumeMounts:
        - name: webui-volume
          mountPath: /app/backend/data
      volumes:
      - name: webui-volume
        persistentVolumeClaim:
          claimName: dekawicara-pvc         